class sensu::params {
  $sensu_rabbitmq_host = hiera('sensu_rabbitmq_host')
  $sensu_rabbitmq_port = hiera('sensu_rabbitmq_port')
  $sensu_rabbitmq_vhost = hiera('sensu_rabbitmq_vhost')
  $sensu_rabbitmq_user = hiera('sensu_rabbitmq_user')
  $sensu_rabbitmq_pass = hiera('sensu_rabbitmq_pass')
  $sensu_redis_host = hiera('sensu_redis_host')
  $sensu_redis_port = hiera('sensu_redis_port')
  $sensu_api_host = hiera('sensu_api_host')
  $sensu_api_port = hiera('sensu_api_port')
  $sensu_dashboard_host = hiera('sensu_dashboard_host')
  $sensu_dashboard_port = hiera('sensu_dashboard_port')
  $sensu_dashboard_user = hiera('sensu_dashboard_user')
  $sensu_dashboard_pass = hiera('sensu_dashboard_pass')
}
