#! /usr/bin/ruby
#
# External node script for Nucleo ENC
#
# == puppet.conf Configuration
#
#  [main]
#  external_nodes = /path/to/external_node
#  node_terminus = exec

require 'yaml'
require 'uri'
require 'net/http'

API_URL = "https://nucleo.arcus.io/api/v1"

NODE = ARGV.first

url = ENV['ARCUS_API_URL'] || API_URL
api_key = ENV['ARCUS_API_KEY'] || nil
uri = URI.parse("#{url}/nodes/#{NODE}/enc")
require 'net/https' if uri.scheme == 'https'

request = Net::HTTP::Get.new(uri.path, initheader = {'Accept' => 'text/yaml', 'api-key' => api_key})
http = Net::HTTP.new(uri.host, uri.port)
if uri.scheme == 'https'
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_PEER
end
result = http.start {|http| http.request(request)}

case result
when Net::HTTPSuccess; puts result.body; exit 0
else; STDERR.puts "Error: #{result.code} #{result.message.strip}\n#{result.body}"; exit 1
end
